name: clougo
description: CloUGO — red social.
publish_to: "none"
version: 0.4.2+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  supabase_flutter: ^2.8.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
